process.on('uncaughtException', (error: Error) => {
    console.error('ðŸ’¥ ERRO FATAL (Uncaught Exception): O processo serÃ¡ encerrado.');
    console.error(`Mensagem: ${error.message}`);
    console.error('Stack Trace:', error.stack);
    process.exit(1);
});

// Captura rejeiÃ§Ãµes de Promises que nÃ£o tÃªm um .catch()
process.on('unhandledRejection', (reason: any, promise: Promise<any>) => {
    console.error('ðŸš¨ REJEIÃ‡ÃƒO NÃƒO TRATADA:', reason);
    console.error('Promise que falhou:', promise);
    process.exit(1);
});

import app from "./app";

const PORT = process.env.PORT || 3000;

async function startApp() {
    try {
        app.listen(PORT, () => {
            console.log(`Server running on http://localhost:${PORT}`);
        });
    } catch (error) {
        console.error("Erro ao iniciar o servidor ou DB:", error);
        process.exit(1);
    }
}

startApp();
